### ISSUE TITLE
Meta issue for syntax improvements in Pulse

### ISSUE THREAD

**Issue by aseemr** [FStarLang/pulse#269]
- [x] `fn (p:int -> int) ...` doesn't parse, it has to be written as `fn (p:(int -> int)) ...` (note the extra parenthesis around the arrow)
- [x] `let _ : t = e;` doesn't parse, it has to be written as `let _u : t = e`
- [x] refinement types annotation `x:int { p x }` doesn't work, it has to be written as `x:(x:int { p x })`
